version: 2
jobs:
  build:
    working_directory: ~/jsoncomparator
    docker:
      - image: circleci/openjdk:8-jdk-stretch
    steps:
      - checkout
      - restore_cache:
          key: jsoncomparator-{{ checksum "pom.xml" }}
      - run: mvn dependency:go-offline
      - save-cache:
          paths:
            - ~/.m2
          key: jsoncomparator-{{ checksum "pom.xml" }}
      - run: mvn package
      - store_test_results:
          path: target/surefire-reports
      - store_artifacts:
          path: target/json-comparator-0.1.jar