version: 2
jobs:
  build:
    working_directory: ~/jsoncomparator
    docker:
      - image: circleci/openjdk:11-jdk-stretch
    steps:
      - checkout
      - restore_cache:
          key: jsoncomparator-{{ checksum "pom.xml" }}
      - run: ./mvnw dependency:go-offline
      - save-cache:
          paths:
            - ~/.m2
          key: jsoncomparator-{{ checksum "pom.xml" }}
      - run: ./mvnw clean verify package
      - store_test_results:
          path: target/surefire-reports
      - store_artifacts:
          path: target